on:
  issues:
    types: [opened]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: ./
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          close: true